version: "3.8"
    
services:
  jupyter:
#    build: 
#      context: .
#      dockerfile: Dockerfile
    image: jupyter/minimal-notebook:lab-3.1.12
    ports: 
      - 58889:8889
    volumes:
      - /Users/sachinkoli/appl/jupyter-notebooks:/home/jovyan/jupyter-notebooks
    environment:
      notebook-dir: /appl/jupyter-notebooks
    networks: 
      - jupyter-dev-network

networks:
  jupyter-dev-network:

