version: "3.8"
    
services:
  kaggle:
#    build: 
#      context: .
#      dockerfile: python3.9-Dockerfile
    image: gcr.io/kaggle-images/python:v104
    ports: 
      - 58080:8080
    volumes:
      - /Users/sachinkoli/appl/kaggle-notebooks:/home/jupyter/kaggle-notebooks
    environment:
      notebook-dir: /appl/kaggle-notebooks
    networks: 
      - kaggle-dev-network

networks:
  kaggle-dev-network:

