version: "3.8"
    
services:
  python3.9:
#    build: 
#      context: .
#      dockerfile: python3.9-Dockerfile
    image: kolisachint/python3.9:ubuntu20.04 
    ports: 
      - 55003:5000
    volumes:
      - /Users/sachinkoli/appl/my-secrets:/my-secrets
      - /Users/sachinkoli/appl/data:/appl/
    environment:
      GIT_SRC: git@github.com:kolisachint/faker-to-csv.git
    networks: 
      - python-dev-network

networks:
  python-dev-network:

