version: "3.8"
    
services:
  python3.9:
    build: 
      context: .
      dockerfile: python3.9-Dockerfile
    image: python3.9:ubuntu20.04 
    ports: 
      - 55000:5000
      - 58080:8080
      - 50080:80
      - 50443:443
    volumes:
      - /Users/sachinkoli/appl/my-secrets:/my-secrets
    environment:
      GIT_SRC: git@github.com:kolisachint/rest-api-example.git
    networks: 
      - python-dev-network

networks:
  python-dev-network:


# docker-compose -f python3.9-DockerCompose.yml up 