version: "3.9"
    
services:
  python3.9:
    build: 
      context: .
      dockerfile: python3.9-Dockerfile
    image: python3.9:ubuntu20.04 
    ports: 
      - 127.0.0.1::58080:8080
      - 127.0.0.1::50080:80
      - 127.0.0.1::50443:443
      - 127.0.0.1::55000:5000
    volumes:
      - /Users/sachinkoli/appl/my-secrets:/my-secrets
    environment:
      GIT_SRC: git@github.com:kolisachint/rest-api-example.git


# docker-compose -f python3.9-DockerCompose.yml up 